name: "godot-ci export"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  GODOT_VERSION: 4.2.2
  ITCH_GAME_ID: "earthquake"

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot --headless --verbose --export-release "Web" ./build/web/index.html

      - name: Deploy to itch.io
        if: startsWith(github.ref, 'refs/tags/')
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          itchUsername: ${{secrets.ITCH_USERNAME}}
          itchGameId: ${{env.ITCH_GAME_ID}}
          gameData: ./build/web
          buildChannel: "webgl"
